# Generated by Django 2.1.5 on 2019-01-18 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, verbose_name='Nom')),
                ('code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Code')),
            ],
            options={
                'verbose_name': 'Compagnie',
            },
        ),
        migrations.CreateModel(
            name='Compte_gl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numéro')),
                ('description', models.CharField(max_length=60, verbose_name='Description')),
                ('sens', models.CharField(choices=[('DT', 'DT'), ('CT', 'CT'), (' ', ' ')], default=' ', max_length=2, verbose_name='Sens du solde')),
                ('type', models.CharField(choices=[('0', 'Poste'), ('1', 'Rubrique'), ('2', 'Total'), ('3', 'Titre')], default=' ', max_length=1, verbose_name='Type de compte')),
                ('solde', models.DecimalField(decimal_places=3, default=0.0, max_digits=12, verbose_name='Solde')),
                ('inactif', models.BooleanField(default=False, verbose_name='Inactif')),
            ],
        ),
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('code_iso', models.CharField(max_length=3, verbose_name='Code ISO')),
                ('symbole', models.CharField(max_length=3, verbose_name='Symbole')),
                ('taux_toCAD', models.DecimalField(decimal_places=10, default='1', max_digits=13, verbose_name='Taux vers ($CA)')),
                ('taux_inverse', models.DecimalField(decimal_places=10, default='1', max_digits=13, verbose_name='Taux inverse')),
                ('date_taux', models.DateField(verbose_name='Date des taux')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('banque_heure', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, verbose_name='Heure(s) en banque')),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Taux horaire')),
                ('compagnie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Compagnie', verbose_name='Compagnie')),
                ('superviseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Employe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employé',
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Numéro')),
                ('description', models.CharField(max_length=60, verbose_name='Description')),
                ('type', models.CharField(choices=[('PO', 'Positif'), ('NE', 'Négatif')], default='PO', max_length=2, verbose_name='Type de tache:')),
            ],
            options={
                'verbose_name': 'Tâche',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='compte_gl',
            name='devise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Devise', verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='compte_gl',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Employe'),
        ),
    ]
