# Generated by Django 2.1.5 on 2019-02-22 21:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='# Référence:')),
                ('designation', models.CharField(max_length=100, verbose_name='Désignation:')),
            ],
            options={
                'verbose_name': 'Famille',
                'verbose_name_plural': 'Familles',
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom:')),
            ],
        ),
        migrations.CreateModel(
            name='LienNM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pe', models.IntegerField(verbose_name='# sur le PE:')),
                ('quantite', models.IntegerField(verbose_name='Quantité:')),
            ],
        ),
        migrations.CreateModel(
            name='LienPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pe', models.IntegerField(verbose_name='# sur le PE:')),
                ('quantite', models.IntegerField(verbose_name='Quantité:')),
            ],
        ),
        migrations.CreateModel(
            name='Nm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='# Référence:')),
                ('designation', models.CharField(max_length=100, verbose_name='Désignation:')),
                ('categorie', models.CharField(choices=[('AS', 'Assy System'), ('WP', 'Wiring Pneumatic'), ('WE', 'Wiring Electric'), ('MA', 'Machine'), ('SO', 'Software'), ('RF', 'Rétrofit'), ('MO', 'Modernisation'), ('RE', 'Réparation'), ('SC', 'Setup Clamp')], default='AS', max_length=2, verbose_name='Catégorie de NM:')),
                ('liens', models.ManyToManyField(related_name='related_to', through='gpao.LienNM', to='gpao.Nm', verbose_name='Contient les NMs suivant:')),
            ],
            options={
                'verbose_name': 'Nomenclature',
                'verbose_name_plural': 'Nomenclatures',
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='Pe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='# Référence:')),
                ('plan', models.FileField(upload_to="PLANS D'ENSEMBLE (PE-XXXX)")),
            ],
            options={
                'verbose_name': "Plan d'ensemble",
                'verbose_name_plural': "Plan d'ensembles",
                'ordering': ['reference'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=30, unique=True, verbose_name='# Référence:')),
                ('plan', models.FileField(blank=True, null=True, upload_to='PLANS DE DEFINITION (X__-XXXX)')),
                ('designation', models.CharField(max_length=100, verbose_name='Désignation:')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date:')),
                ('format_papier', models.CharField(choices=[('LT', 'Letter'), ('LD', 'Ledger'), ('A4', 'A4'), ('OT', 'Autre')], default='LT', max_length=2, verbose_name='Format papier:')),
                ('ref_commercial', models.CharField(default='XXX', max_length=30, verbose_name='Référence commercial:')),
                ('ref_mecanique', models.CharField(default='XXX', max_length=30, verbose_name='Référence mécanique:')),
                ('brute', models.CharField(default='XXX', max_length=30, verbose_name='Brute:')),
                ('soudure', models.BooleanField(default=False, verbose_name='Soudure:')),
                ('finition', models.CharField(choices=[('XX', 'Aucune'), ('ZP', 'Zinc Plated'), ('AN', 'Anodisation'), ('PE', 'Peint'), ('PL', 'Placage'), ('OB', 'Oxide Noir'), ('BR', 'Brossé'), ('OT', 'Autre')], default='XX', max_length=2, verbose_name='Finition:')),
                ('commentaires', models.CharField(blank=True, max_length=200, null=True, verbose_name='Commentaires:')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Prix:')),
                ('famille', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gpao.Famille', verbose_name='Famille:')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gpao.Fournisseur', verbose_name='Fournisseur:')),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
                'ordering': ['reference'],
            },
        ),
        migrations.AddField(
            model_name='nm',
            name='liens_piece',
            field=models.ManyToManyField(related_name='related_piece', through='gpao.LienPiece', to='gpao.Piece', verbose_name='Contient les Pièces suivante:'),
        ),
        migrations.AddField(
            model_name='nm',
            name='pe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gpao.Pe', verbose_name="Plan d'ensemble:"),
        ),
        migrations.AddField(
            model_name='lienpiece',
            name='from_nm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_nm_p', to='gpao.Nm'),
        ),
        migrations.AddField(
            model_name='lienpiece',
            name='to_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_piece', to='gpao.Piece', verbose_name='Lié à Pièce:'),
        ),
        migrations.AddField(
            model_name='liennm',
            name='from_nm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_nm', to='gpao.Nm'),
        ),
        migrations.AddField(
            model_name='liennm',
            name='to_nm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_nm', to='gpao.Nm', verbose_name='Lié à NM:'),
        ),
    ]
