# Generated by Django 2.1.5 on 2019-02-22 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, unique=True, verbose_name='Nom')),
                ('nom_en', models.CharField(max_length=30, unique=True, verbose_name='Nom Anglais')),
            ],
            options={
                'ordering': ['nom', 'nom_en'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephonne', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de téléphonne')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de fax')),
                ('siteweb', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site web')),
                ('ratio', models.DecimalField(decimal_places=2, default='1', max_digits=5, verbose_name='Ratio')),
                ('ratio_us', models.DecimalField(decimal_places=2, default='1', max_digits=5, verbose_name='Ratio US')),
                ('actif', models.BooleanField(verbose_name='Actif')),
                ('devise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources.Devise', verbose_name='Devise')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Numéro')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails')),
                ('details_en', models.TextField(blank=True, null=True, verbose_name='Détails Anglais')),
                ('prix_fournisseur', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Prix du fournisseur')),
                ('dateprix', models.DateField(blank=True, null=True, verbose_name='Date du prix')),
                ('escompte', models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Escompte (%)')),
                ('ratio', models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Ratio')),
                ('ratio_us', models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Ratio US')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('actif', models.BooleanField(verbose_name='Actif')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listes_de_prix.Categorie', verbose_name='Catégorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listes_de_prix.Fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'ordering': ['numero'],
                'permissions': (('afficher_listes_prix', 'Afficher les listes de prix'), ('afficher_listes_prix_en', 'Afficher les listes de prix US')),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100, unique=True, verbose_name='Numéro')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails')),
                ('details_en', models.TextField(blank=True, null=True, verbose_name='Détails Anglais')),
                ('prix_fournisseur', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Prix du fournisseur')),
                ('dateprix', models.DateField(blank=True, null=True, verbose_name='Date du prix')),
                ('escompte', models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Escompte (%)')),
                ('ratio', models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Ratio')),
                ('ratio_us', models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Ratio US')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='listes_de_prix.Fournisseur', verbose_name='Fournisseur')),
                ('machines', models.ManyToManyField(related_name='options_machine', to='listes_de_prix.Machine')),
            ],
            options={
                'ordering': ['numero'],
                'permissions': (('afficher_listes_prix', 'Afficher les listes de prix'), ('afficher_listes_prix_en', 'Afficher les listes de prix US')),
                'abstract': False,
            },
        ),
    ]
