# Generated by Django 2.1.5 on 2019-02-22 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Entrez un nom', max_length=50, verbose_name='Nom')),
                ('adresse', models.CharField(blank=True, max_length=50, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=50, verbose_name='Ville')),
                ('province_etat', models.CharField(blank=True, max_length=50, verbose_name='Province/État')),
                ('postal_code', models.CharField(blank=True, max_length=50, verbose_name='Code Postal')),
                ('pays', models.CharField(blank=True, max_length=50, verbose_name='Pays')),
                ('telephonne', models.CharField(blank=True, max_length=50, verbose_name='Numéro de téléphonne')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Numéro de fax')),
            ],
            options={
                'verbose_name': 'Compagnie',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(blank=True, max_length=50, verbose_name='Prénom')),
                ('nom', models.CharField(blank=True, max_length=50, verbose_name='Nom')),
                ('fonction', models.CharField(blank=True, max_length=50, verbose_name='Fonction')),
                ('telephonne', models.CharField(blank=True, max_length=50, verbose_name='Numéro de téléphonne')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Adresse courriel')),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Compagnie', verbose_name='Compagnie')),
            ],
            options={
                'verbose_name': 'Contact',
                'ordering': ['prenom', 'nom'],
            },
        ),
    ]
