# Generated by Django 2.1.5 on 2019-02-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True, verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Materiel_Eugenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_materiel.Categorie', verbose_name='Catégorie')),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_materiel.Fournisseur', verbose_name='Fournisseur')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projets.Projet_Eugenie', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Matériel Eugénie',
                'verbose_name_plural': 'Matériel Eugénie',
            },
        ),
    ]
