# Generated by Django 2.1.5 on 2019-02-22 21:03

import compte.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projets', '0001_initial'),
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense_Eci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('detail', models.CharField(max_length=50, verbose_name='Détails')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant sans taxes')),
                ('tps', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='TPS/TVH')),
                ('tvq', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='TVQ')),
                ('photo', models.ImageField(blank=True, upload_to=compte.models.upload_path)),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé?')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé?')),
                ('approved_on', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approving_employe', to='ressources.Employe', verbose_name='Approuvé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources.Employe', verbose_name='Employé')),
                ('gl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources.Compte_gl', verbose_name='GL')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projets.Projet_Eugenie', verbose_name='Numéro de projet')),
            ],
            options={
                'verbose_name': 'Dépense Eugénie Canada',
                'verbose_name_plural': 'Dépenses Eugénie Canada',
                'permissions': (('creer_cdd_eci', 'Creer une depense EuGénie'), ('admin_cdd_eci', 'Superviseur pour EuGénie Canada Inc.')),
            },
        ),
        migrations.CreateModel(
            name='Depense_Tpe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('detail', models.CharField(max_length=50, verbose_name='Détails')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant sans taxes')),
                ('tps', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='TPS/TVH')),
                ('tvq', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='TVQ')),
                ('photo', models.ImageField(blank=True, upload_to=compte.models.upload_path)),
                ('approuve', models.BooleanField(default=False, verbose_name='Approuvé?')),
                ('paye', models.BooleanField(default=False, verbose_name='Payé?')),
                ('approved_on', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approving_employe_tpe', to='ressources.Employe', verbose_name='Approuvé par')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources.Employe', verbose_name='Employé')),
                ('gl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources.Compte_gl', verbose_name='GL')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projets.Projet_TPE', verbose_name='Numéro de projet')),
            ],
            options={
                'verbose_name': 'Dépense Techno-Pro Expert',
                'verbose_name_plural': 'Dépenses Techno-Pro Expert',
                'permissions': (('creer_cdd_tpe', 'Creer une depense Techno-Pro Expert'), ('admin_cdd_tpe', 'Superviseur pour Techno-Pro Expert')),
            },
        ),
        migrations.CreateModel(
            name='Petite_Caisse_Eci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('detail', models.CharField(max_length=50, verbose_name='Détails')),
                ('montant', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Montant sans taxes')),
                ('tps', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='TPS/TVH')),
                ('tvq', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='TVQ')),
                ('nb_penny', models.IntegerField(default=0, verbose_name='Nombre de 1 sous')),
                ('nb_nickel', models.IntegerField(default=0, verbose_name='Nombre de 5 sous')),
                ('nb_dime', models.IntegerField(default=0, verbose_name='Nombre de 10 sous')),
                ('nb_quarter', models.IntegerField(default=0, verbose_name='Nombre de 25 sous')),
                ('nb_un', models.IntegerField(default=0, verbose_name='Nombre de 1$')),
                ('nb_deux', models.IntegerField(default=0, verbose_name='Nombre de 2$')),
                ('nb_cinq', models.IntegerField(default=0, verbose_name='Nombre de billet de 5')),
                ('nb_dix', models.IntegerField(default=0, verbose_name='Nombre de billet de 10')),
                ('nb_vingt', models.IntegerField(default=0, verbose_name='Nombre de billet de 20')),
                ('nb_cinquante', models.IntegerField(default=0, verbose_name='Nombre de billet de 50')),
                ('nb_cent', models.IntegerField(default=0, verbose_name='Nombre de billet de 100')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources.Employe', verbose_name='Employé')),
                ('gl', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ressources.Compte_gl', verbose_name='GL')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projets.Projet_Eugenie', verbose_name='Numéro de projet')),
            ],
            options={
                'verbose_name': 'Petite caisse Eugénie Canada',
                'verbose_name_plural': 'Petite caisse Eugénie Canada',
                'permissions': (('creer_pc_eci', 'Creer depense petite caisse EuGénie'), ('admin_pc_eci', 'Superviseur pour EuGénie Canada Inc.')),
            },
        ),
    ]
